### ISSUE TITLE
Thank you for your blog post + a small issue

### ISSUE THREAD

**Issue by totaltrash** [reisub/phoenix-with-npm#1]
Hi Dino, thank you for your blog post. Since NPM was removed from phoenix I've usually gone with a hybrid approach (esbuild still installed by mix), but your way is really nice, so simple to reason with and easy to extend.

There is a potential issue with the blog post. Since phx 1.7.1, Heroicons are getting installed into `assets/vendor`, so someone running `rm -rf assets/vendor` will lose their heroicons.

Thanks again!

**Comment by reisub** [comment]
Thanks Darren, changed to `rm assets/vendor/topbar.js` to fix the issue!
